### ISSUE TITLE
geopose sample customization help

### ISSUE THREAD

**Issue by carrbrpoa** [argonjs/samples#12]
Hello,

I've changed Georgia Tech coordinates to something close to me (110 meters) in geopose sample and the buzz box doesn't show in Android browser, just desktop's Chrome. Any ideas?

Thanks

**Comment by blairmacintyre** [comment]
Is it getting geolocation (does it show a location in the info box on the screen)?  Some browsers will only let you use the geolocation APIs over secure connections.  I tried it on Android just now, and over `http://` I got no geolocation, but over `https://` I was asked about it.

**Comment by carrbrpoa** [comment]
Hey Blair,

It is showing the coordinates and the distances (chrome implements that
https security stuff to grab user's location, but Android's built in
browser doesn't, so it works).

**Comment by blairmacintyre** [comment]
The Android Chrome browser I'm using implements https security stuff;  are you using a recent version of Android?  Is the "box" showing up, just not the GT box?  Does it look similar to the one on desktop?

**Comment by carrbrpoa** [comment]
That's it, but I just tested now, from farther, and the buzz with custom
location (closer to where I was) appears. I'll check tomorrow again, from
the place I was. By the way, is it possible to add some notion of distance
when dealing with this sample? I see the buzz box even greater than brown
box close to me, but it is 2km away. What could I do to really appears that
buzz box is farther? (I can open a new issue if needed :))

**Comment by speigg** [comment]
The buzz box in this sample is actually pretty huge (1km x 1km x 1km, I think). 
You can try rendering with fog to help create the illusion of distance.

**Comment by blairmacintyre** [comment]
Ah, yes.  Ok, the deal is probably location accuracy.  If you are INSIDE the box, you won't see it (backface culling in the renderer).  And the location of desktop (using location APIs) or mobile GPS are TERRIBLE.  If you are outside under open sky it's better.

As for making the sample work at different distances;  sure, you can change anything.  We really just created the sample to show folks how to do "something" with geospatial coordinates in argon and three.js.   I don't want to make it too much more complicated, but if you have suggestions, we can change it.

**Comment by carrbrpoa** [comment]
@speigg I see, I'll try that.
@blairmacintyre actually I think Argon and this sample is really nice. I'm coming from "normal" 2d web mapping (Leaflet, Geoserver, etc.) for some adventures in 3D world :)

One possible application I have in mind is for example someone targeting the floor with his mobile device and seeing water or gas tubing under him, possibly being able to see some textual details.
The closest thing I found until now to do something like this is Argon.

**Comment by blairmacintyre** [comment]
Thanks @carrbrpoa !

The biggest challenge with doing geospatial AR is the poor quality of GPS/location sensor in mobile devices.  So, if your location is off by a few meters (best case) and changing ~1 time/sec with a noticeable jump, it makes it hard to look down and see things on the ground.
